@URL = http://localhost:3000 
# @URL =  https://rest-server-basic.onrender.com


### CREATE TASK

POST {{URL}}/api/task
content-type: application/json

{
    "title": "title task",
    "description": "descr task",
    "userId": "65451e2933f162ecc56968a5"
}

### GET TASK BY ID

GET {{URL}}/api/task/653703e36355fb52be588d94
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTJkZWU0ZTZkZjRiYzI0NDIyMmRiNmEiLCJpYXQiOjE2OTkwNDk5MDksImV4cCI6MTY5OTA2NDMwOX0.AtHjfxzFr4L8q9V4279GYVCEulXEG5YQ8l1-88x2RBk

### GET TASK BY USER ID

GET {{URL}}/api/task/byUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTJkZWU0ZTZkZjRiYzI0NDIyMmRiNmEiLCJpYXQiOjE2OTkwNDk5MDksImV4cCI6MTY5OTA2NDMwOX0.AtHjfxzFr4L8q9V4279GYVCEulXEG5YQ8l1-88x2RBk

# content-type: application/json

# {
   
#     "userId": "652db9ba7a78b3a09cbfc5a5"
# }
