@URL = http://localhost:3000 
# @URL =  https://rest-server-basic.onrender.com


### CREATE TASK

POST {{URL}}/api/task
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTJkZWU0ZTZkZjRiYzI0NDIyMmRiNmEiLCJpYXQiOjE2OTk3NTA2ODMsImV4cCI6MTY5OTc2NTA4M30.uGkGFG9NPqW57v15tCfLku_mTTzcPzXfJ7MAcy5N5s8

{
    "title": "title task new",
    "description": "descr task",
    "userId": "65451e2933f162ecc56968a5"
}

### GET TASK BY ID

GET {{URL}}/api/task/653703e36355fb52be588d94
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTJkZWU0ZTZkZjRiYzI0NDIyMmRiNmEiLCJpYXQiOjE2OTkwNDk5MDksImV4cCI6MTY5OTA2NDMwOX0.AtHjfxzFr4L8q9V4279GYVCEulXEG5YQ8l1-88x2RBk

### GET TASK BY USER ID

GET {{URL}}/api/task/byUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTJkZWU0ZTZkZjRiYzI0NDIyMmRiNmEiLCJpYXQiOjE2OTkwNDk5MDksImV4cCI6MTY5OTA2NDMwOX0.AtHjfxzFr4L8q9V4279GYVCEulXEG5YQ8l1-88x2RBk

### DELETE TASK
DELETE {{URL}}/api/task/654c15f402f591a8aa8432a2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTJkZWU0ZTZkZjRiYzI0NDIyMmRiNmEiLCJpYXQiOjE2OTk0ODk2OTYsImV4cCI6MTY5OTUwNDA5Nn0.IF6eydse-JuYBk2h52TJI-_nfMbKJE4BBN9zGPuQHoI

### UPDATE TASK

PUT {{URL}}/api/task/655012fbc88d01fb3c1aec01
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NTJkZWU0ZTZkZjRiYzI0NDIyMmRiNmEiLCJpYXQiOjE2OTk3NTA2ODMsImV4cCI6MTY5OTc2NTA4M30.uGkGFG9NPqW57v15tCfLku_mTTzcPzXfJ7MAcy5N5s8

{
    "title": "title task new",
    "description": "descr task"
}
